export const Items = [
  {
    id: 1,
    name: "Oil Filter",
    quantity: 60,
    price: 8.45,
    category: "Engine Parts",
    description: "Oil Filter for optimal vehicle performance.",
    supplier: "Supplier 2",
    costPrice: 4.75,
    msrp: 13.65,
    discount: 6,
    taxRate: 8,
    shippingWeight: 0.75,
    shippingDimensions: "6x5x3 inches",
    shippingCarrier: "UPS",
    shippingCost: 2.75,
  },
  {
    id: 2,
    name: "Spark Plug",
    quantity: 70,
    price: 11.9,
    category: "Ignition System",
    description: "Spark Plug for optimal vehicle performance.",
    supplier: "Supplier 3",
    costPrice: 7.5,
    msrp: 17.3,
    discount: 7,
    taxRate: 8,
    shippingWeight: 1.0,
    shippingDimensions: "7x6x4 inches",
    shippingCarrier: "USPS",
    shippingCost: 3.5,
  },
  {
    id: 3,
    name: "Air Filter",
    quantity: 80,
    price: 15.35,
    category: "Air Intake System",
    description: "Air Filter for optimal vehicle performance.",
    supplier: "Supplier 4",
    costPrice: 10.25,
    msrp: 20.95,
    discount: 8,
    taxRate: 8,
    shippingWeight: 1.25,
    shippingDimensions: "8x7x2 inches",
    shippingCarrier: "DHL",
    shippingCost: 4.25,
  },
  {
    id: 4,
    name: "Fuel Pump",
    quantity: 90,
    price: 18.8,
    category: "Fuel System",
    description: "Fuel Pump for optimal vehicle performance.",
    supplier: "Supplier 5",
    costPrice: 13.0,
    msrp: 24.6,
    discount: 9,
    taxRate: 8,
    shippingWeight: 1.5,
    shippingDimensions: "9x8x3 inches",
    shippingCarrier: "FedEx",
    shippingCost: 5.0,
  },
  {
    id: 5,
    name: "Clutch Kit",
    quantity: 100,
    price: 22.25,
    category: "Transmission System",
    description: "Clutch Kit for optimal vehicle performance.",
    supplier: "Supplier 6",
    costPrice: 15.75,
    msrp: 28.25,
    discount: 10,
    taxRate: 8,
    shippingWeight: 1.75,
    shippingDimensions: "10x9x4 inches",
    shippingCarrier: "UPS",
    shippingCost: 5.75,
  },
  {
    id: 6,
    name: "Radiator",
    quantity: 110,
    price: 25.7,
    category: "Cooling System",
    description: "Radiator for optimal vehicle performance.",
    supplier: "Supplier 7",
    costPrice: 18.5,
    msrp: 31.9,
    discount: 11,
    taxRate: 8,
    shippingWeight: 2.0,
    shippingDimensions: "11x10x2 inches",
    shippingCarrier: "USPS",
    shippingCost: 6.5,
  },
  {
    id: 7,
    name: "Timing Belt",
    quantity: 120,
    price: 29.15,
    category: "Lighting System",
    description: "Timing Belt for optimal vehicle performance.",
    supplier: "Supplier 8",
    costPrice: 21.25,
    msrp: 35.55,
    discount: 12,
    taxRate: 8,
    shippingWeight: 2.25,
    shippingDimensions: "12x11x3 inches",
    shippingCarrier: "DHL",
    shippingCost: 7.25,
  },
  {
    id: 8,
    name: "Alternator",
    quantity: 130,
    price: 32.6,
    category: "Suspension System",
    description: "Alternator for optimal vehicle performance.",
    supplier: "Supplier 9",
    costPrice: 24.0,
    msrp: 39.2,
    discount: 13,
    taxRate: 8,
    shippingWeight: 2.5,
    shippingDimensions: "13x4x4 inches",
    shippingCarrier: "FedEx",
    shippingCost: 8.0,
  },
  {
    id: 9,
    name: "Headlights",
    quantity: 140,
    price: 36.05,
    category: "Body Parts",
    description: "Headlights for optimal vehicle performance.",
    supplier: "Supplier 10",
    costPrice: 26.75,
    msrp: 42.85,
    discount: 14,
    taxRate: 8,
    shippingWeight: 2.75,
    shippingDimensions: "14x5x2 inches",
    shippingCarrier: "UPS",
    shippingCost: 8.75,
  },
  {
    id: 10,
    name: "Wheel Bearings",
    quantity: 150,
    price: 39.5,
    category: "Braking System",
    description: "Wheel Bearings for optimal vehicle performance.",
    supplier: "Supplier 11",
    costPrice: 29.5,
    msrp: 46.5,
    discount: 5,
    taxRate: 8,
    shippingWeight: 3.0,
    shippingDimensions: "5x6x3 inches",
    shippingCarrier: "USPS",
    shippingCost: 9.5,
  },
  {
    id: 11,
    name: "Muffler",
    quantity: 160,
    price: 42.95,
    category: "Engine Parts",
    description: "Muffler for optimal vehicle performance.",
    supplier: "Supplier 12",
    costPrice: 32.25,
    msrp: 50.15,
    discount: 6,
    taxRate: 8,
    shippingWeight: 3.25,
    shippingDimensions: "6x7x4 inches",
    shippingCarrier: "DHL",
    shippingCost: 10.25,
  },
  {
    id: 12,
    name: "Windshield Wipers",
    quantity: 170,
    price: 46.4,
    category: "Ignition System",
    description: "Windshield Wipers for optimal vehicle performance.",
    supplier: "Supplier 13",
    costPrice: 35.0,
    msrp: 53.8,
    discount: 7,
    taxRate: 8,
    shippingWeight: 3.5,
    shippingDimensions: "7x8x2 inches",
    shippingCarrier: "FedEx",
    shippingCost: 11.0,
  },
  {
    id: 13,
    name: "Battery",
    quantity: 180,
    price: 49.85,
    category: "Air Intake System",
    description: "Battery for optimal vehicle performance.",
    supplier: "Supplier 14",
    costPrice: 37.75,
    msrp: 57.45,
    discount: 8,
    taxRate: 8,
    shippingWeight: 3.75,
    shippingDimensions: "8x9x3 inches",
    shippingCarrier: "UPS",
    shippingCost: 11.75,
  },
  {
    id: 14,
    name: "Shock Absorbers",
    quantity: 190,
    price: 53.3,
    category: "Fuel System",
    description: "Shock Absorbers for optimal vehicle performance.",
    supplier: "Supplier 15",
    costPrice: 40.5,
    msrp: 61.1,
    discount: 9,
    taxRate: 8,
    shippingWeight: 4.0,
    shippingDimensions: "9x10x4 inches",
    shippingCarrier: "USPS",
    shippingCost: 12.5,
  },
  {
    id: 15,
    name: "Control Arm",
    quantity: 200,
    price: 56.75,
    category: "Transmission System",
    description: "Control Arm for optimal vehicle performance.",
    supplier: "Supplier 16",
    costPrice: 43.25,
    msrp: 64.75,
    discount: 10,
    taxRate: 8,
    shippingWeight: 4.25,
    shippingDimensions: "10x11x2 inches",
    shippingCarrier: "DHL",
    shippingCost: 13.25,
  },
  {
    id: 16,
    name: "Catalytic Converter",
    quantity: 210,
    price: 60.2,
    category: "Cooling System",
    description: "Catalytic Converter for optimal vehicle performance.",
    supplier: "Supplier 17",
    costPrice: 46.0,
    msrp: 68.4,
    discount: 11,
    taxRate: 8,
    shippingWeight: 4.5,
    shippingDimensions: "11x4x3 inches",
    shippingCarrier: "FedEx",
    shippingCost: 14.0,
  },
  {
    id: 17,
    name: "Thermostat",
    quantity: 220,
    price: 63.65,
    category: "Lighting System",
    description: "Thermostat for optimal vehicle performance.",
    supplier: "Supplier 18",
    costPrice: 48.75,
    msrp: 72.05,
    discount: 12,
    taxRate: 8,
    shippingWeight: 4.75,
    shippingDimensions: "12x5x4 inches",
    shippingCarrier: "UPS",
    shippingCost: 14.75,
  },
  {
    id: 18,
    name: "Water Pump",
    quantity: 230,
    price: 67.1,
    category: "Suspension System",
    description: "Water Pump for optimal vehicle performance.",
    supplier: "Supplier 19",
    costPrice: 51.5,
    msrp: 75.7,
    discount: 13,
    taxRate: 8,
    shippingWeight: 5.0,
    shippingDimensions: "13x6x2 inches",
    shippingCarrier: "USPS",
    shippingCost: 15.5,
  },
  {
    id: 19,
    name: "Drive Shaft",
    quantity: 240,
    price: 70.55,
    category: "Body Parts",
    description: "Drive Shaft for optimal vehicle performance.",
    supplier: "Supplier 20",
    costPrice: 54.25,
    msrp: 79.35,
    discount: 14,
    taxRate: 8,
    shippingWeight: 5.25,
    shippingDimensions: "14x7x3 inches",
    shippingCarrier: "DHL",
    shippingCost: 16.25,
  },
  {
    id: 20,
    name: "Steering Rack",
    quantity: 250,
    price: 74.0,
    category: "Braking System",
    description: "Steering Rack for optimal vehicle performance.",
    supplier: "Supplier 1",
    costPrice: 57.0,
    msrp: 83.0,
    discount: 5,
    taxRate: 8,
    shippingWeight: 0.5,
    shippingDimensions: "5x8x4 inches",
    shippingCarrier: "FedEx",
    shippingCost: 17.0,
  },
  {
    id: 21,
    name: "Exhaust Pipe",
    quantity: 260,
    price: 77.45,
    category: "Engine Parts",
    description: "Exhaust Pipe for optimal vehicle performance.",
    supplier: "Supplier 2",
    costPrice: 59.75,
    msrp: 86.65,
    discount: 6,
    taxRate: 8,
    shippingWeight: 0.75,
    shippingDimensions: "6x9x2 inches",
    shippingCarrier: "UPS",
    shippingCost: 17.75,
  },
  {
    id: 22,
    name: "Axle Shaft",
    quantity: 270,
    price: 80.9,
    category: "Ignition System",
    description: "Axle Shaft for optimal vehicle performance.",
    supplier: "Supplier 3",
    costPrice: 62.5,
    msrp: 90.3,
    discount: 7,
    taxRate: 8,
    shippingWeight: 1.0,
    shippingDimensions: "7x10x3 inches",
    shippingCarrier: "USPS",
    shippingCost: 18.5,
  },
  {
    id: 23,
    name: "Turbocharger",
    quantity: 280,
    price: 84.35,
    category: "Air Intake System",
    description: "Turbocharger for optimal vehicle performance.",
    supplier: "Supplier 4",
    costPrice: 65.25,
    msrp: 93.95,
    discount: 8,
    taxRate: 8,
    shippingWeight: 1.25,
    shippingDimensions: "8x11x4 inches",
    shippingCarrier: "DHL",
    shippingCost: 19.25,
  },
  {
    id: 24,
    name: "EGR Valve",
    quantity: 290,
    price: 87.8,
    category: "Fuel System",
    description: "EGR Valve for optimal vehicle performance.",
    supplier: "Supplier 5",
    costPrice: 68.0,
    msrp: 97.6,
    discount: 9,
    taxRate: 8,
    shippingWeight: 1.5,
    shippingDimensions: "9x4x2 inches",
    shippingCarrier: "FedEx",
    shippingCost: 20.0,
  },
  {
    id: 25,
    name: "Oxygen Sensor",
    quantity: 300,
    price: 91.25,
    category: "Transmission System",
    description: "Oxygen Sensor for optimal vehicle performance.",
    supplier: "Supplier 6",
    costPrice: 70.75,
    msrp: 101.25,
    discount: 10,
    taxRate: 8,
    shippingWeight: 1.75,
    shippingDimensions: "10x5x3 inches",
    shippingCarrier: "UPS",
    shippingCost: 20.75,
  },
  {
    id: 26,
    name: "Fan Belt",
    quantity: 310,
    price: 94.7,
    category: "Cooling System",
    description: "Fan Belt for optimal vehicle performance.",
    supplier: "Supplier 7",
    costPrice: 73.5,
    msrp: 104.9,
    discount: 11,
    taxRate: 8,
    shippingWeight: 2.0,
    shippingDimensions: "11x6x4 inches",
    shippingCarrier: "USPS",
    shippingCost: 21.5,
  },
  {
    id: 27,
    name: "Power Steering Pump",
    quantity: 320,
    price: 98.15,
    category: "Lighting System",
    description: "Power Steering Pump for optimal vehicle performance.",
    supplier: "Supplier 8",
    costPrice: 76.25,
    msrp: 108.55,
    discount: 12,
    taxRate: 8,
    shippingWeight: 2.25,
    shippingDimensions: "12x7x2 inches",
    shippingCarrier: "DHL",
    shippingCost: 2.25,
  },
  {
    id: 28,
    name: "Engine Mount",
    quantity: 330,
    price: 101.6,
    category: "Suspension System",
    description: "Engine Mount for optimal vehicle performance.",
    supplier: "Supplier 9",
    costPrice: 79.0,
    msrp: 112.2,
    discount: 13,
    taxRate: 8,
    shippingWeight: 2.5,
    shippingDimensions: "13x8x3 inches",
    shippingCarrier: "FedEx",
    shippingCost: 3.0,
  },
  {
    id: 29,
    name: "Cylinder Head",
    quantity: 340,
    price: 105.05,
    category: "Body Parts",
    description: "Cylinder Head for optimal vehicle performance.",
    supplier: "Supplier 10",
    costPrice: 81.75,
    msrp: 115.85,
    discount: 14,
    taxRate: 8,
    shippingWeight: 2.75,
    shippingDimensions: "14x9x4 inches",
    shippingCarrier: "UPS",
    shippingCost: 3.75,
  },
  {
    id: 30,
    name: "Tail Lights",
    quantity: 350,
    price: 108.5,
    category: "Braking System",
    description: "Tail Lights for optimal vehicle performance.",
    supplier: "Supplier 11",
    costPrice: 84.5,
    msrp: 119.5,
    discount: 5,
    taxRate: 8,
    shippingWeight: 3.0,
    shippingDimensions: "5x10x2 inches",
    shippingCarrier: "USPS",
    shippingCost: 4.5,
  },
  {
    id: 31,
    name: "Hood Latch",
    quantity: 360,
    price: 111.95,
    category: "Engine Parts",
    description: "Hood Latch for optimal vehicle performance.",
    supplier: "Supplier 12",
    costPrice: 87.25,
    msrp: 123.15,
    discount: 6,
    taxRate: 8,
    shippingWeight: 3.25,
    shippingDimensions: "6x11x3 inches",
    shippingCarrier: "DHL",
    shippingCost: 5.25,
  },
  {
    id: 32,
    name: "Fender Liner",
    quantity: 370,
    price: 115.4,
    category: "Ignition System",
    description: "Fender Liner for optimal vehicle performance.",
    supplier: "Supplier 13",
    costPrice: 90.0,
    msrp: 126.8,
    discount: 7,
    taxRate: 8,
    shippingWeight: 3.5,
    shippingDimensions: "7x4x4 inches",
    shippingCarrier: "FedEx",
    shippingCost: 6.0,
  },
  {
    id: 33,
    name: "Door Handle",
    quantity: 380,
    price: 118.85,
    category: "Air Intake System",
    description: "Door Handle for optimal vehicle performance.",
    supplier: "Supplier 14",
    costPrice: 92.75,
    msrp: 130.45,
    discount: 8,
    taxRate: 8,
    shippingWeight: 3.75,
    shippingDimensions: "8x5x2 inches",
    shippingCarrier: "UPS",
    shippingCost: 6.75,
  },
  {
    id: 34,
    name: "Grille",
    quantity: 390,
    price: 122.3,
    category: "Fuel System",
    description: "Grille for optimal vehicle performance.",
    supplier: "Supplier 15",
    costPrice: 95.5,
    msrp: 134.1,
    discount: 9,
    taxRate: 8,
    shippingWeight: 4.0,
    shippingDimensions: "9x6x3 inches",
    shippingCarrier: "USPS",
    shippingCost: 7.5,
  },
  {
    id: 35,
    name: "Floor Mats",
    quantity: 400,
    price: 125.75,
    category: "Transmission System",
    description: "Floor Mats for optimal vehicle performance.",
    supplier: "Supplier 16",
    costPrice: 98.25,
    msrp: 137.75,
    discount: 10,
    taxRate: 8,
    shippingWeight: 4.25,
    shippingDimensions: "10x7x4 inches",
    shippingCarrier: "DHL",
    shippingCost: 8.25,
  },
  {
    id: 36,
    name: "Car Cover",
    quantity: 410,
    price: 129.2,
    category: "Cooling System",
    description: "Car Cover for optimal vehicle performance.",
    supplier: "Supplier 17",
    costPrice: 101.0,
    msrp: 141.4,
    discount: 11,
    taxRate: 8,
    shippingWeight: 4.5,
    shippingDimensions: "11x8x2 inches",
    shippingCarrier: "FedEx",
    shippingCost: 9.0,
  },
  {
    id: 37,
    name: "Spark Plug Wires",
    quantity: 420,
    price: 132.65,
    category: "Lighting System",
    description: "Spark Plug Wires for optimal vehicle performance.",
    supplier: "Supplier 18",
    costPrice: 3.75,
    msrp: 145.05,
    discount: 12,
    taxRate: 8,
    shippingWeight: 4.75,
    shippingDimensions: "12x9x3 inches",
    shippingCarrier: "UPS",
    shippingCost: 9.75,
  },
  {
    id: 38,
    name: "Fuel Injector",
    quantity: 430,
    price: 136.1,
    category: "Suspension System",
    description: "Fuel Injector for optimal vehicle performance.",
    supplier: "Supplier 19",
    costPrice: 6.5,
    msrp: 148.7,
    discount: 13,
    taxRate: 8,
    shippingWeight: 5.0,
    shippingDimensions: "13x10x4 inches",
    shippingCarrier: "USPS",
    shippingCost: 10.5,
  },
  {
    id: 39,
    name: "Coolant Reservoir",
    quantity: 440,
    price: 139.55,
    category: "Body Parts",
    description: "Coolant Reservoir for optimal vehicle performance.",
    supplier: "Supplier 20",
    costPrice: 9.25,
    msrp: 152.35,
    discount: 14,
    taxRate: 8,
    shippingWeight: 5.25,
    shippingDimensions: "14x11x2 inches",
    shippingCarrier: "DHL",
    shippingCost: 11.25,
  },
  {
    id: 40,
    name: "Parking Brake Cable",
    quantity: 450,
    price: 143.0,
    category: "Braking System",
    description: "Parking Brake Cable for optimal vehicle performance.",
    supplier: "Supplier 1",
    costPrice: 12.0,
    msrp: 156.0,
    discount: 5,
    taxRate: 8,
    shippingWeight: 0.5,
    shippingDimensions: "5x4x3 inches",
    shippingCarrier: "FedEx",
    shippingCost: 12.0,
  },
  {
    id: 41,
    name: "Hood Struts",
    quantity: 460,
    price: 146.45,
    category: "Engine Parts",
    description: "Hood Struts for optimal vehicle performance.",
    supplier: "Supplier 2",
    costPrice: 14.75,
    msrp: 159.65,
    discount: 6,
    taxRate: 8,
    shippingWeight: 0.75,
    shippingDimensions: "6x5x4 inches",
    shippingCarrier: "UPS",
    shippingCost: 12.75,
  },
  {
    id: 42,
    name: "Rear View Mirror",
    quantity: 470,
    price: 149.9,
    category: "Ignition System",
    description: "Rear View Mirror for optimal vehicle performance.",
    supplier: "Supplier 3",
    costPrice: 17.5,
    msrp: 163.3,
    discount: 7,
    taxRate: 8,
    shippingWeight: 1.0,
    shippingDimensions: "7x6x2 inches",
    shippingCarrier: "USPS",
    shippingCost: 13.5,
  },
  {
    id: 43,
    name: "Side Mirror",
    quantity: 480,
    price: 153.35,
    category: "Air Intake System",
    description: "Side Mirror for optimal vehicle performance.",
    supplier: "Supplier 4",
    costPrice: 20.25,
    msrp: 166.95,
    discount: 8,
    taxRate: 8,
    shippingWeight: 1.25,
    shippingDimensions: "8x7x3 inches",
    shippingCarrier: "DHL",
    shippingCost: 14.25,
  },
  {
    id: 44,
    name: "Horn",
    quantity: 490,
    price: 6.8,
    category: "Fuel System",
    description: "Horn for optimal vehicle performance.",
    supplier: "Supplier 5",
    costPrice: 23.0,
    msrp: 170.6,
    discount: 9,
    taxRate: 8,
    shippingWeight: 1.5,
    shippingDimensions: "9x8x4 inches",
    shippingCarrier: "FedEx",
    shippingCost: 15.0,
  },
  {
    id: 45,
    name: "Door Seal",
    quantity: 500,
    price: 10.25,
    category: "Transmission System",
    description: "Door Seal for optimal vehicle performance.",
    supplier: "Supplier 6",
    costPrice: 25.75,
    msrp: 174.25,
    discount: 10,
    taxRate: 8,
    shippingWeight: 1.75,
    shippingDimensions: "10x9x2 inches",
    shippingCarrier: "UPS",
    shippingCost: 15.75,
  },
  {
    id: 46,
    name: "Transmission Filter",
    quantity: 510,
    price: 13.7,
    category: "Cooling System",
    description: "Transmission Filter for optimal vehicle performance.",
    supplier: "Supplier 7",
    costPrice: 28.5,
    msrp: 177.9,
    discount: 11,
    taxRate: 8,
    shippingWeight: 2.0,
    shippingDimensions: "11x10x3 inches",
    shippingCarrier: "USPS",
    shippingCost: 16.5,
  },
  {
    id: 47,
    name: "Ignition Coil",
    quantity: 520,
    price: 17.15,
    category: "Lighting System",
    description: "Ignition Coil for optimal vehicle performance.",
    supplier: "Supplier 8",
    costPrice: 31.25,
    msrp: 181.55,
    discount: 12,
    taxRate: 8,
    shippingWeight: 2.25,
    shippingDimensions: "12x11x4 inches",
    shippingCarrier: "DHL",
    shippingCost: 17.25,
  },
  {
    id: 48,
    name: "Starter Motor",
    quantity: 530,
    price: 20.6,
    category: "Suspension System",
    description: "Starter Motor for optimal vehicle performance.",
    supplier: "Supplier 9",
    costPrice: 34.0,
    msrp: 185.2,
    discount: 13,
    taxRate: 8,
    shippingWeight: 2.5,
    shippingDimensions: "13x4x2 inches",
    shippingCarrier: "FedEx",
    shippingCost: 18.0,
  },
  {
    id: 49,
    name: "Brake Rotor",
    quantity: 540,
    price: 24.05,
    category: "Body Parts",
    description: "Brake Rotor for optimal vehicle performance.",
    supplier: "Supplier 10",
    costPrice: 36.75,
    msrp: 188.85,
    discount: 14,
    taxRate: 8,
    shippingWeight: 2.75,
    shippingDimensions: "14x5x3 inches",
    shippingCarrier: "UPS",
    shippingCost: 18.75,
  },
  {
    id: 50,
    name: "Brake Pads",
    quantity: 50,
    price: 27.5,
    category: "Braking System",
    description: "Brake Pads for optimal vehicle performance.",
    supplier: "Supplier 11",
    costPrice: 39.5,
    msrp: 192.5,
    discount: 5,
    taxRate: 8,
    shippingWeight: 3.0,
    shippingDimensions: "5x6x4 inches",
    shippingCarrier: "USPS",
    shippingCost: 19.5,
  },
];

export const ProductColumns = [
  { field: "id", headerName: "ID", minwidth: 100, resizable: false, flex: 1 },
  {
    field: "name",
    headerName: "Name",
    minwidth: 200,
    resizable: false,
    flex: 1,
  },
  {
    field: "quantity",
    headerName: "Quantity",
    minwidth: 100,
    resizable: false,
    flex: 1,
  },
  {
    field: "price",
    headerName: "Price",
    minwidth: 100,
    resizable: false,
    flex: 1,
  },
  {
    field: "category",
    headerName: "Category",
    minwidth: 200,
    resizable: false,
    flex: 1,
  },
];
